# Generated by Django 4.2 on 2024-11-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likedislike', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedislike',
            options={'verbose_name_plural': 'Likes and Dislikes'},
        ),
        migrations.AlterUniqueTogether(
            name='likedislike',
            unique_together=set(),
        ),
    ]
