# Generated by Django 4.2 on 2024-10-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_has_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='has_sizes_clothes',
        ),
        migrations.AddField(
            model_name='product',
            name='has_sizes_shoes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
